### ISSUE TITLE
Question about dexsearch

### ISSUE THREAD

**Issue by zan-preston** [kubukoz/nix-config#1]
👋 Hi there!

While my nix config and home-manager set up is much less full-featured than yours, I'm installing `dexsearch` the same way you are with `node2nix`. The package installs and runs fine, but no output ever makes it to my clipboard.

The only difference is I'm having to run `nix-shell -p nodePackages.node2nix --command "node2nix -i ./node-packages.json -o node-packages.nix --nodejs-18"` instead because `nodejs-14` is EOL. I'm not sure if there's something broken there that's causing the issue and it's just failing silently? (Full disclosure, I haven't tried building the project locally because I'm 100% inexperienced with scalajs and don't have an environment set up for it.)

I tried perusing through here to see if you were doing anything that might be addressing this issue if you were having it at one point, but I'm not seeing anything.

If you have any ideas, that'd be amazing! Otherwise, no biggie, this was just a shot in the dark 😄

**Comment by kubukoz** [comment]
Interesting... are you on Mac? As far as I can see, my dexsearch runs on node 20:

```
nix-store --query --tree $(nix run nixpkgs#chase -- $(which dexsearch))

/nix/store/wwbsvwcsdi4hx70g1pbbixa7a1mihjfp-dexsearch-0.1.5
└───/nix/store/5c0nzhy641v5hqnpb056vvdgg3pl9hgc-nodejs-20.11.1
    ├───/nix/store/1zadybrxmi2s2y32fi8dbsfj7hkpg5k9-openssl-3.0.13
    │   └───/nix/store/1zadybrxmi2s2y32fi8dbsfj7hkpg5k9-openssl-3.0.13 [...]
    ├───/nix/store/9ajqklp51cgxr26176fd82l3li9v81fa-openssl-3.0.13-dev
    │   ├───/nix/store/1zadybrxmi2s2y32fi8dbsfj7hkpg5k9-openssl-3.0.13 [...]
    │   ├───/nix/store/4lz20bvlfp40ylgjqjq76jhwvrsx4hb8-openssl-3.0.13-bin
    │   │   ├───/nix/store/1zadybrxmi2s2y32fi8dbsfj7hkpg5k9-openssl-3.0.13 [...]
    │   │   ├───/nix/store/d6vr31gydldgf4al6cyi6fy6z6d44n3n-bash-5.2p26
    │   │   │   └───/nix/store/d6vr31gydldgf4al6cyi6fy6z6d44n3n-bash-5.2p26 [...]
    │   │   └───/nix/store/4lz20bvlfp40ylgjqjq76jhwvrsx4hb8-openssl-3.0.13-bin [...]
    │   └───/nix/store/9ajqklp51cgxr26176fd82l3li9v81fa-openssl-3.0.13-dev [...]
    ├───/nix/store/9r3s31g515vq71kjcx5c6ny5mfijay5x-libSystem-11.0.0
    │   └───/nix/store/9r3s31g515vq71kjcx5c6ny5mfijay5x-libSystem-11.0.0 [...]
    ├───/nix/store/d6vr31gydldgf4al6cyi6fy6z6d44n3n-bash-5.2p26 [...]
    ├───/nix/store/wzfjvi4911armpapj817kx9pczqmp2ik-libuv-1.48.0
    │   └───/nix/store/wzfjvi4911armpapj817kx9pczqmp2ik-libuv-1.48.0 [...]
    ├───/nix/store/f2ag314ia0px9hmpxwfc3c5lcbx026vq-libuv-1.48.0-dev
    │   ├───/nix/store/wzfjvi4911armpapj817kx9pczqmp2ik-libuv-1.48.0 [...]
    │   └───/nix/store/f2ag314ia0px9hmpxwfc3c5lcbx026vq-libuv-1.48.0-dev [...]
    ├───/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6
    │   └───/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6 [...]
    ├───/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6
    │   ├───/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6 [...]
    │   └───/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6 [...]
    ├───/nix/store/pmic5z7141cnsxp3ga5rrvaynw1rfnwn-zlib-1.3.1
    │   └───/nix/store/pmic5z7141cnsxp3ga5rrvaynw1rfnwn-zlib-1.3.1 [...]
    ├───/nix/store/mbsl2p81gz4hg6xlz4y3amyn5wg2fwdc-zlib-1.3.1-dev
    │   ├───/nix/store/pmic5z7141cnsxp3ga5rrvaynw1rfnwn-zlib-1.3.1 [...]
    │   └───/nix/store/mbsl2p81gz4hg6xlz4y3amyn5wg2fwdc-zlib-1.3.1-dev [...]
    ├───/nix/store/qymlh2mv3cm6gsxmlz0mpf2yyvjmhyy1-icu4c-73.2
    │   ├───/nix/store/d6vr31gydldgf4al6cyi6fy6z6d44n3n-bash-5.2p26 [...]
    │   ├───/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6 [...]
    │   ├───/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6 [...]
    │   └───/nix/store/qymlh2mv3cm6gsxmlz0mpf2yyvjmhyy1-icu4c-73.2 [...]
    ├───/nix/store/rjgv94p1nnj02v0f9r2jpann9x02b4vw-libcxx-16.0.6-dev
    │   └───/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6 [...]
    ├───/nix/store/zylssblj7387l1x95jl0k7ljcanp4lb0-icu4c-73.2-dev
    │   ├───/nix/store/d6vr31gydldgf4al6cyi6fy6z6d44n3n-bash-5.2p26 [...]
    │   ├───/nix/store/g9x4r8l8hjk3vfj26k90p3rjc6g8j3i6-libcxxabi-16.0.6 [...]
    │   ├───/nix/store/j3yw5w8pbdv4argnmx7i4i0lvglnh7ll-libcxx-16.0.6 [...]
    │   ├───/nix/store/qymlh2mv3cm6gsxmlz0mpf2yyvjmhyy1-icu4c-73.2 [...]
    │   └───/nix/store/zylssblj7387l1x95jl0k7ljcanp4lb0-icu4c-73.2-dev [...]
    └───/nix/store/5c0nzhy641v5hqnpb056vvdgg3pl9hgc-nodejs-20.11.1 [...]

```

and it works fine with the clipboard.

Perhaps there's a permission that needs to be given to Node for it to manage your clipboard, and you're missing it?

I would also suggest looking for help in the library Dexsearch uses to copy to the clipboard, [clipboardy](https://github.com/sindresorhus/clipboardy) - one thing you can try now is [clipboard-cli](https://github.com/sindresorhus/clipboard-cli), which is available in Nixpkgs as `nodePackages.clipboard-cli`. That working (or not working) could be another hint.

**Comment by kubukoz** [comment]
also, can you screenrecord how you're using it? Just to exclude the possibility of PEBCAK 😅

**Comment by zan-preston** [comment]
I am on a Mac. I'll give clipboardy-cli a shot and try to troubleshoot some more. 

Thanks for the tips!

**Comment by zan-preston** [comment]
> also, can you screenrecord how you're using it? Just to exclude the possibility of PEBCAK 😅 

For sure!

I'm away from my machine for the rest of the evening, but I'll do that tomorrow morning!

**Comment by zan-preston** [comment]
Odd. clipboard-cli seems to work just fine. I can have it access the contents of the clipboard repeatedly. Then, after I run `dexsearch` the clipboard contents have been cleared.


https://github.com/kubukoz/nix-config/assets/91221230/8cec95e2-6456-41b4-ba63-2edc8be08fd7

**Comment by kubukoz** [comment]
ah, there it is - you're not actually selecting any modules to copy. You need to mark them with the spacebar :)

so it's making an empty string for you, and copying that - making your clipboard empty.

https://github.com/kubukoz/nix-config/assets/894884/a1d0c32f-6c98-49c8-926f-e6f4073d93c3

**Comment by kubukoz** [comment]
BTW I think this is a case that should be prevented by dexsearch (and vscode-scaladex too): not selecting any modules should just warn you about that rather than proceed to give you an empty string. I'm a bit too lazy to make a proper issue for that though 😅

**Comment by zan-preston** [comment]
🤦 I'm an idiot.

Thank you!

**Comment by kubukoz** [comment]
nah, it happens! Glad I could help.
